version: '3.1'

services:
  tweetfetch:
    image: 'ronnyma/tweetfetch:latest'
    restart: unless-stopped
    secrets:
      - consumer_key
      - consumer_secret
      - access_token
      - access_token_secret
    depends_on:
      - mongodb
    networks:
      - tweet

  mongodb:
    image: 'mongo:3.4.1'
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - /var/data/mongo:/data/db
    networks:
      - tweet

networks:
  tweet:
    driver: bridge
secrets:
  consumer_key:
    file: /var/secrets/ck
  consumer_secret:
    file: /var/secrets/cs
  access_token:
    file: /var/secrets/at
  access_token_secret:
    file: /var/secrets/ats
